const { withAppBuildGradle } = require('@expo/config-plugins');
const { mergeContents } = require('@expo/config-plugins/build/utils/generateCode');

const SIGNING_CONFIG_TAG = 'android-release-signing-config';
const APPLY_SIGNING_TAG = 'android-release-signing-apply';

/**
 * Injects a `signingConfigs.release` block into the freshly-generated
 * android/app/build.gradle and points `buildTypes.release` at it.
 *
 * android/ is never committed (it's regenerated by `expo prebuild` every
 * time), so release signing can't live in a manually-edited build.gradle —
 * it has to be re-applied by this plugin on every prebuild, local or CI.
 *
 * Reads credentials from environment variables at Gradle build time
 * (never written to gradle.properties):
 *   ANDROID_RELEASE_STORE_FILE, ANDROID_RELEASE_STORE_PASSWORD,
 *   ANDROID_RELEASE_KEY_ALIAS, ANDROID_RELEASE_KEY_PASSWORD
 */
function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(
        `withAndroidReleaseSigning only supports Groovy build.gradle files (got: ${config.modResults.language}).`
      );
    }

    const signingConfigBlock = [
      '    release {',
      '        storeFile file(System.getenv("ANDROID_RELEASE_STORE_FILE") ?: "release.keystore")',
      '        storePassword System.getenv("ANDROID_RELEASE_STORE_PASSWORD")',
      '        keyAlias System.getenv("ANDROID_RELEASE_KEY_ALIAS")',
      '        keyPassword System.getenv("ANDROID_RELEASE_KEY_PASSWORD")',
      '    }',
    ].join('\n');

    const merged = mergeContents({
      tag: SIGNING_CONFIG_TAG,
      src: config.modResults.contents,
      newSrc: signingConfigBlock,
      anchor: /signingConfigs\s*\{/,
      offset: 1,
      comment: '//',
    });

    let contents = merged.contents;

    // Appended after the `android { ... }` closure instead of regex-splicing
    // into buildTypes.release, since Groovy evaluates top-to-bottom and that
    // block's exact text drifts across RN/Expo template patches.
    const applyMarker = `// @generated begin ${APPLY_SIGNING_TAG}`;
    if (!contents.includes(applyMarker)) {
      contents =
        `${contents.trimEnd()}\n\n${applyMarker}\n` +
        'android.buildTypes.release.signingConfig = android.signingConfigs.release\n' +
        `// @generated end ${APPLY_SIGNING_TAG}\n`;
    }

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withAndroidReleaseSigning;
